version: 2
updates:
    # Enable version updates for npm
    - package-ecosystem: 'npm'
      # Look for `package.json` and `lock` files in the `root` directory
      directory: '/'
      # Pause creating new PRs until existing ones are merged or closed
      open-pull-requests-limit: 1
      # Check the npm registry for updates every day (weekdays)
      schedule:
          interval: 'daily'
          time: '04:00'
          timezone: Asia/Calcutta
