#!/usr/bin/env sh
# NOTE: Run chmod +x .husky/pre-commit && git update-index --chmod=+x .husky/pre-commit if not executable
. "$(dirname -- "$0")/_/husky.sh"

pnpm exec biome check --staged --files-ignore-unknown=true --no-errors-on-unmatched
pnpm exec tsc --noEmit