name: CI

# todo: add lints.
# todo: add tests. tests may not require build. install dependencies and start tests.

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build 👷
        run: npm run build
